server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500 # 1:N 조회시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.type: trace
    com.app: debug # package 수정

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

kakao:
  client:
    id: 85ce68b97843d98acc3042fc4c3fd7eb
    secret: N2As2KGYv9ucHPN17cwQP0YW3RqXhOAW

token:
  secret: 7JWI7J6I7Yq466CI7J2Y7J24IOyVhOyngOyKpOyVhOyngA==  # 임의의 문자열
  access-token-expiration-time: 900000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)